services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '9001:9001'
    environment:
      - PORT=9001
    volumes:
      - ./src:/usr/src/app/src
