services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9009:9009'
    environment:
      - PORT=9009
      - POSTGRES_PASSWORD=2002
      - DB_USER=postgres
      - DB_NAME=todostask
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=2002
      - DB_USER=postgres
      - DB_NAME=todostask
