services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '9009:9009'
    environment:
      - PORT=9009
      - DB_PASSWORD=2002
      - DB_USER=postgres
      - DB_NAME=todostask
    volumes:
      - ./src:/usr/src/app/src
